language: php
php:
    - 7.0
    - 7.1
services:
    - memcached
    - mysql
before_install:
    - "sudo apt-get remove mysql-common mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5 mysql-client-core-5.5"
    - "sudo apt-get autoremove"
    - "sudo apt-get install libaio1"
    - "wget -O mysql-5.6.14.deb http://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.14-debian6.0-x86_64.deb/from/http://cdn.mysql.com/"
    - "sudo dpkg -i mysql-5.6.14.deb"
    - "sudo cp /opt/mysql/server-5.6/support-files/mysql.server /etc/init.d/mysql.server"
    - "sudo ln -s /opt/mysql/server-5.6/bin/* /usr/bin/"
    - "sudo sed -i'' 's/table_cache/table_open_cache/' /etc/mysql/my.cnf"
    - "sudo sed -i'' 's/log_slow_queries/slow_query_log/' /etc/mysql/my.cnf"
    - "sudo sed -i'' 's/basedir[^=]\\+=.*$/basedir = \\/opt\\/mysql\\/server-5.6/' /etc/mysql/my.cnf"
    - "sudo /etc/init.d/mysql.server start"
    - mysql --version
    - mysql -e "SELECT VERSION();"
    - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
install:
    - composer install
before_script:
    - curl http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -o php-cs-fixer.phar
    - mysql -u root -e "CREATE DATABASE dev;" && mysql -u root dev < vendor/pskuza/php_session/tests/mysql.sql && mysql -u root dev < tests/mysql.sql
script:
    - php php-cs-fixer.phar fix -v --dry-run --diff src
    - "./vendor/bin/phpunit"
    - mysql -u root dev -e "Select * FROM sessions;"
    - mysql -u root dev -e "Select * FROM users;"
    - mysql -u root dev -e "Select * FROM logins;"
    - mysql -u root dev -e "Select * FROM confirmation;"
    - mysql -u root dev -e "Select * FROM reset;"
    - mysql -u root dev -e "Select * FROM fail_users;"
    - mysql -u root dev -e "Select * FROM fail_ip;"
